services:
  client:
    build:
      context: .
      target: client
    ports:
    - '3000:3000'
    networks:
    - my_network
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - '85:80'
    depends_on:
      - client
    networks:
      - my_network
    volumes:
    - logs:/var/log/nginx
    
networks:
  my_network:

volumes:
  logs:
  
