services:
  client:
    build: .
    ports:
    - '3000:3000'
    networks:
    - my_network
  nginx:
    image: nginx:latest
    ports:
      - '85:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
    networks:
      - my_network
    

networks:
  my_network:
